services:
  mysql:
    image: mysql:8.0.33
    volumes:
      - ~/app/identity_service/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=identity_service
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3307:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: ['CMD', 'mysql', '-e', 'SHOW DATABASES;']
      interval: 5s
      timeout: 5s
      retries: 10
