name: Deploy Identity Service

on:
  push:
    branches:
      - dev

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: SSH to cloud server and clone repository
        run: |
          sshpass -p KYo0p3hn5Rp1h91C ssh -o StrictHostKeyChecking=no root@103.82.25.94
          pwd
          sudo su
          cd /
          ls -la

      - name: Pull Source & Checkout
        run: |
          git clone https://github.com/microservices-traning/identity-service.git
          pwd && ls -lta
          cd identity-service && pwd && ls -lta

      - name: Run Docker Compose
        run: |
          docker build -t huyha25062000/identity-service:latest .
          docker-compose -p identity-service stop
          docker-compose -p identity-service down
          docker-compose -p identity-service up -d
