name: Deploy Identity Service

on:
  push:
    branches:
      - dev

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 103.82.25.94
          username: root
          password: KYo0p3hn5Rp1h91C
          port: 22
          script: whoami

      - name: Pull Source
        run: git clone https://github.com/microservices-traning/identity-service.git && pwd

      - name: Cd
        run: cd identity-service

      - name: Run Docker Compose
        run: docker-compose -p identity-service pull && docker-compose -p identity-service stop && docker-compose -p identity-service down && docker-compose -p identity-service up -d
